services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}  # Uses the password from your .env file
      MYSQL_DATABASE: employee
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: employee-app
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}  # Uses the datasource URL from your .env file
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}  # Uses the username from your .env file
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}  # Uses the password from your .env file
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_URL=${FRONTEND_URL}  # Uses the frontend URL from your .env file
    depends_on:
      - mysql
    # Optional: You can add wait-for-it or similar here to ensure MySQL is ready

volumes:
  mysql-data:
