version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: employee-app
    ports:
      - "8085:8085"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/employee
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - mysql

volumes:
  mysql-data:
